services:
  - type: web
    name: KhetalPuraDairy
    env: static
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /<*>   # Matches all routes
        destination: /index.html
